# Generated by Django 5.1.1 on 2024-11-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
    ]
