# Generated by Django 5.1.1 on 2024-11-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='signature',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Signature',
        ),
    ]
