# Generated by Django 5.1.1 on 2024-11-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_signature_authorized_task_signature_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='document_file',
            field=models.FileField(upload_to='signed_documents/'),
        ),
    ]
