# Generated by Django 5.1.1 on 2024-11-11 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_signature_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signature",
            name="document_file",
        ),
    ]
