# Generated by Django 5.1.1 on 2024-11-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_signature_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="public_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
